
spring:
  datasource:
   # url: jdbc:postgresql://localhost:5432/LMS_DB
   # username: postgres  #changed as per Local DB
   # password: admin  #changed as per Local DB
    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME} 
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
 

app:
  frontend.url: ${FRONTEND_URL_HEROKU}
  #frontend.url: https://lms-frontend.herokuapp.com

